### ISSUE TITLE
ERROR: Unknown input file type. It should be a docx, xlsx, pptx, odt, ods, odp, xhtml, html or an xml file

### ISSUE THREAD

**Issue by jreyesr** [jreyesr/n8n-nodes-carbonejs#1]
The Render node no longer works. Instead, it fails with the following error:

```
ERROR: Unknown input file type. It should be a docx, xlsx, pptx, odt, ods, odp, xhtml, html or an xml file
```

Example workflow:
![image](https://github.com/jreyesr/n8n-nodes-carbonejs/assets/23390438/ce6a8482-4ac3-4f26-bb8d-6f4f74f75a36)

The HTTP node makes a GET request to <https://github.com/carboneio/carbone/raw/master/examples/movies.docx>, which is a valid DOCX file. The Carbone node renders it with the context `{}`.

The error happens when running the Render node:

![image](https://github.com/jreyesr/n8n-nodes-carbonejs/assets/23390438/bf88e6d3-1c57-4b6d-b12e-6bcc6eda3fd7)

**Comment by jreyesr** [comment]
Seems to have fixed itself, or at least I haven't been able to reproduce it anymore

**Comment by Vladimir-Va** [comment]
Hello, I'm experimenting with the carbone js node and getting an error in the topic.
Is this possible if n8n works in queue mode?
```
To avoid this, change the N8N_DEFAULT_BINARY_DATA_MODE environment variable to filesystem. This causes n8n to save data to disk, instead of using memory.

If you're using queue mode, keep this to default. n8n doesn't support filesystem mode with queue mode.
```

**Comment by jreyesr** [comment]
Hello @Vladimir-Va! I've moved your question to Discussion #8, because this issue #1 is already closed
