### ISSUE TITLE
Options in Context

### ISSUE THREAD

**Issue by mrtnblv** [jreyesr/n8n-nodes-carbonejs#2]
Hello,
Is it possible to pass options to the render nodes? Like "timezone" or "lang".

**Comment by mrtnblv** [comment]
Thank you for your prompt response. I've just realized that it might indeed be possible to add options by introducing some adjustments [here](https://github.com/jreyesr/n8n-nodes-carbonejs/blob/522f395f096b45a671063672fac9462b32d3ded4/nodes/CarboneNode/CarboneUtils.ts#L35): {lang:"fr", timezone:"Europe/Paris"}. This kind of enhancement would be really great!

Thank you for your work on this, much appreciated. Looking forward to the new improvements.

Best

**Comment by jreyesr** [comment]
Hey there @mrtnblv! I've just released v1.1.0, which lets you specify some Options, such as the Locale and Timezone. You'll find them in the Add Option dropdown at the bottom of the Render node options:

![image](https://github.com/jreyesr/n8n-nodes-carbonejs/assets/23390438/f837a334-b531-4c41-900e-ef6576f11f58)

Thanks for raising the issue! Feel free to open new issues if you find any bugs.

**Comment by mrtnblv** [comment]
Thank you so much for the update and for implementing these changes so quickly. I appreciate your dedication. I'm excited to test out these new options right away.
